[workspace]
members = [
  "tictactoe",
  "tictactoe-godot",
]

[profile.dev.package."*"]
# Set the default for dependencies in Development mode.
opt-level = 3

[profile.dev]
# Turn on a small amount of optimisation in Development mode.
opt-level = 1
