name: Continuous Integration
on: push
jobs:
  test:
    name: Test Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package tictactoe
